config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :detail_treatments
  resources :treatments
  resources :sliders
  resources :videos
  resources :events
  mount Ckeditor::Engine => '/ckeditor'
  resources :writers
  resources :articles
  resources :categories
  root 'pages#home'
  resources :appointments
  resources :contacts
  get 'app' => "app#index"
  get 'invoice' => "app#invoice"
  get 'pemeriksaan' => "app#pemeriksaan"
  get 'report' => "app#report"
  get 'app-dokter' => "app#app_dokter"
  get 'contact-us', to: 'pages#contact', as: :contact_us
  get 'create-appointment', to: 'pages#create_appointment', as: :create_appointment
  get 'blog', to: 'pages#blog', as: :list_blog
  resources :users
  resources :setups
  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  get 'list-page', to: 'pages#index', as: :list_pages
  resources :pages, path: ''
  get '/blog/:id', to: 'articles#show', as: :blog_detail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :writer
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  
  has_many :articles
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader

end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  validates :title, presence: true

  mount_uploader :cover_image, ImageUploader

  has_many :sliders, inverse_of: :page
  accepts_nested_attributes_for :sliders, reject_if: :all_blank, allow_destroy: true

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :page, optional:true
  belongs_to :treatment, optional:true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
    extend FriendlyId
    friendly_id :title

    mount_uploader :image, ImageUploader
    mount_uploader :cover_image, ImageUploader

    has_many :sliders, inverse_of: :treatment
    accepts_nested_attributes_for :sliders, reject_if: :all_blank, allow_destroy: true
    has_many :detail_treatments, inverse_of: :treatment
    accepts_nested_attributes_for :detail_treatments, reject_if: :all_blank, allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',doctor:'doctor', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :doctor, -> {where(role: ROLES[:doctor])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_doctor?
    self.role == ROLES[:doctor]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/writer.rb
class Writer < ApplicationRecord
  extend FriendlyId
  friendly_id :title
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :new]
  layout 'admin', only: [:index, :edit, :new]
  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treatment_params
      params.require(:treatment).permit(:title, :cover_image, :image, :content, :meta_description, :treatment_detail_title, :treatment_detail_description,  sliders_attributes: [:id, :image, :caption, :_destroy, :treatment_id], detail_treatments_attributes: [:id, :title, :content, :_destroy, :treatment_id])
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/treatments/_detail_treatment_fields.html.erb
<div class="col-md-12 nested-fields">
  <div class="form-group">
    <%= f.label :title, :class => 'control-label' %>
    <%= f.text_field :title, :class => 'form-control' %>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label' %>
      <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {toolbar: 'mini'} %>
    <%=f.error_span(:content) %>
  </div>

  <div class="mt-3 text-center">
    <%= link_to_remove_association "Remove Detail Treatment", f, class:"btn btn-danger" %>
  </div>
</div>


<script type="text/javascript">
  $('.dropify').dropify();
</script>

app/views/treatments/_form.html.erb
<% if @treatment.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@treatment.errors.count, "error") %> prohibited this treatment from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @treatment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<%= form_for @treatment, :html => { :class => "form-horizontal treatment" } do |f| %>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <%= f.label :title, :class => 'control-label' %>
      <%= f.text_field :title, :class => 'form-control' %>
      <%=f.error_span(:title) %>

      <%= f.label :slug, :class => 'control-label' %>
      <%= f.text_field :slug, :class => 'form-control' %>
      <%=f.error_span(:slug) %>
    </div>
    <div class="form-group">
      <%= f.label :meta_description, :class => 'control-label' %>
      <%= f.text_area :meta_description, :class => 'form-control', rows: 5 %>
      <%=f.error_span(:meta_description) %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h3>Image Thumbail</h3>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :image, :class => 'control-label' %>
        <% if @treatment.image.nil? || @treatment.image.blank? %>
        <%= f.file_field :image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K'  %>
        <% else %>
        <%= f.file_field :image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K' , 'data-default-file' => @treatment.image.url %>
        <% end %>
        <%=f.error_span(:image) %>
      </div>
      <div class="col-md-6">
        <%= f.label :cover_image, :class => 'control-label' %>
        <% if @treatment.cover_image.nil? || @treatment.cover_image.blank? %>
        <%= f.file_field :cover_image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K'  %>
        <% else %>
        <%= f.file_field :cover_image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K' , 'data-default-file' => @treatment.cover_image.url %>
        <% end %>
        <%=f.error_span(:cover_image) %>
      </div>
    </div>
    <hr>
    <h3>Sliders</h3>
    <hr>
    <div class="row" id="sliders">
      <%= f.fields_for :sliders do |slider| %>
      <%= render 'slider_fields', f: slider %>
      <% end %>
      <div class="col-md-4">
        <%= link_to_add_association 'add image', f, :sliders, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {toolbar: 'mini'} %>
          <%=f.error_span(:content) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h3>Treatment Detail</h3>
    <hr>
    <div class="form-group">
      <%= f.label :treatment_detail_title, :class => 'control-label' %>
      <%= f.text_field :treatment_detail_title, :class => 'form-control' %>
      <%=f.error_span(:treatment_detail_title) %>
    </div>
    <div class="form-group">
      <%= f.label :treatment_detail_description, :class => 'control-label' %>
      <%= f.text_area :treatment_detail_description, :class => 'form-control', rows: 5 %>
      <%=f.error_span(:treatment_detail_description) %>
    </div>
    <h3>List Treatment</h3>
    <hr>
    <div class="row" id="sliders">
      <%= f.fields_for :detail_treatments do |detail_treatment| %>
      <%= render 'detail_treatment_fields', f: detail_treatment %>
      <% end %>
      <div class="col-md-4">
        <%= link_to_add_association 'add Detail Treatment', f, :detail_treatments, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-body">

    <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), treatments_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>



<% end %>

app/views/treatments/_slider_fields.html.erb
<div class="col-md-4 nested-fields">
  <div class="form-group">
    <%= f.label :image,"Slider Image", :class => 'control-label' %>
    <% if  f.object.image.nil? or f.object.image.blank? %>
    <%= f.file_field :image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K'  %>
    <% else %>
    <%= f.file_field :image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K' , 'data-default-file' => f.object.image.url %>
    <% end %>
    <%=f.error_span(:image) %>

  </div>
  <div class="form-group">
    <%= f.label :caption,"Alt Image", :class => 'control-label' %>
    <%= f.text_field :caption, :class => 'form-control' %>
    <%=f.error_span(:caption) %>
  </div>

  <div class="mt-3 text-center">
    <%= link_to_remove_association "remove image", f, class:"btn btn-danger" %>
  </div>
</div>


<script type="text/javascript">
  $('.dropify').dropify();
</script>

app/views/treatments/edit.html.erb
<%- model_class = Page -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/treatments/index.html.erb
<%- model_class = Treatment -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_treatment_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th><%= model_class.human_attribute_name(:meta_description) %></th>

                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @treatments.each do |treatment| %>
              <tr>
                <td><%= link_to treatment.id, treatment_path(treatment) %></td>
                <td><%= treatment.title %></td>
                <td><%= treatment.meta_description %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  treatment_path(treatment), :class => 'btn btn-default btn-xs m-1' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_treatment_path(treatment), :class => 'btn btn-default btn-xs m-1' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  treatment_path(treatment),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs m-1 btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/treatments/new.html.erb
<%- model_class = Page -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= pages_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <%= render :partial => 'form' %>
</div>

app/views/treatments/show.html.erb
<div class="quote-area position-relative" style="background: rgba(0, 0, 0, 0) url('<%= @treatment.cover_image %>') no-repeat fixed center bottom / cover ;padding: 200px 0;  position: relative;">
  <div style="position: absolute;top: 0;left: 0; width: 100%;height: 100%; background-color:rgba(6, 6, 6, 0.18);">
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-8 text-center">
        <p style="font-size:30px;color:white;text-transform:uppercase">
          <%= @treatment.title %>
        </p>
      </div>
    </div>
  </div>
</div>
<section class="position-relative" >


  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h1 style="font-weight: 900;">
          <%= @treatment.title %>
        </h1>

        <% unless @treatment.sliders.count == 0 %>
        <div id="treatment_slider" class="carousel slide carousel-fade mt-3" data-ride="carousel">
          <% @treatment.sliders.each do |x, i| %>
          <div class="carousel-inner">
            <div class="carousel-item <% if i == 0 %> active <% end %>">
              <img src="/assets/slider child 1.jpg" alt="" class="w-100">
            </div>
          </div>
          <% end %>
          <a class="carousel-control-prev" href="#treatment_slider" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#treatment_slider" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <% end %>
      </div>
      <div class="col-md-8">
        <%= @treatment.content.html_safe %>
      </div>
    </div>
  </div>
</section>

<% unless @treatment.detail_treatments.empty? %>
<section class="quote-area position-relative" style="background: rgba(0, 0, 0, 0) url('<%= @treatment.cover_image %>') no-repeat fixed center bottom / cover ;padding: 200px 0;  position: relative;">
  <div style="position: absolute;top: 0;left: 0; width: 100%;height: 100%; background-color:rgba(6, 6, 6, 0.7);">
  </div>

  <div class="container position-relative">

    <div class="mb-4">
      <h3 class="text-white"><%= @treatment.treatment_detail_title %></h3>
      <p class="text-white"><%= @treatment.treatment_detail_description %></p>
    </div>

    <div class="row">
      <% @treatment.detail_treatments.each do |x| %>
      <div class="col-md-<%= count_row(@treatment.detail_treatments.count) %>">
        <h3 class="text-white"><%= x.title %></h3>
        <div class="text-white">
          <%= x.content.html_safe %>
        </div>
      </div>
      <% end %>
    </div>

  </div>
</section>

<% end %>