config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :detail_treatments
  resources :treatments
  resources :sliders
  resources :videos
  resources :events
  mount Ckeditor::Engine => '/ckeditor'
  resources :writers
  resources :articles
  resources :categories
  root 'pages#home'
  resources :appointments
  resources :contacts
  get 'app' => "app#index"
  get 'invoice' => "app#invoice"
  get 'pemeriksaan' => "app#pemeriksaan"
  get 'report' => "app#report"
  get 'app-dokter' => "app#app_dokter"
  get 'contact-us', to: 'pages#contact', as: :contact_us
  get 'create-appointment', to: 'pages#create_appointment', as: :create_appointment
  get 'blog', to: 'pages#blog', as: :list_blog
  resources :users
  resources :setups
  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  get 'list-page', to: 'pages#index', as: :list_pages
  resources :pages, path: ''
  get '/blog/:id', to: 'articles#show', as: :blog_detail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :writer
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  
  has_many :articles
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader

end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  validates :title, presence: true

  mount_uploader :cover_image, ImageUploader

  has_many :sliders, inverse_of: :page
  accepts_nested_attributes_for :sliders, reject_if: :all_blank, allow_destroy: true

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :page, optional:true
  belongs_to :treatment, optional:true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
    extend FriendlyId
    friendly_id :title

    mount_uploader :image, ImageUploader
    mount_uploader :cover_image, ImageUploader

    has_many :sliders, inverse_of: :treatment
    accepts_nested_attributes_for :sliders, reject_if: :all_blank, allow_destroy: true
    has_many :detail_treatments, inverse_of: :treatment
    accepts_nested_attributes_for :detail_treatments, reject_if: :all_blank, allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',doctor:'doctor', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :doctor, -> {where(role: ROLES[:doctor])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_doctor?
    self.role == ROLES[:doctor]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/writer.rb
class Writer < ApplicationRecord
  extend FriendlyId
  friendly_id :title
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  layout 'admin', except: [:show]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @last_event = Event.last
    @related = Article.all.where.not(id: @article.id).where(category_id:  @article.category_id).limit(5)
    prepare_meta_tags(
    title: @article.title,
    description: @article.meta_description,
    image: @article.image,
    twitter: {
      site_name: "BEHAVE CLINIC | #{@article.title || @article.title}" ,
      site: '@behave_clinic',
      creator: '@behave_clinic',
      card: 'summary',
      description:   @article.meta_description || ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(250),
      title: @article.title || @article.title,
      image: request.protocol + request.host_with_port + @article.image.url
    },
    og: {
      url: request.protocol + request.host_with_port+"/blog/"+ @article.slug,
      site_name:  "BEHAVE CLINIC | #{@article.title || @article.title}" ,
      title: @article.title || @article.title,
      image: request.protocol + request.host_with_port + @article.image.url,
      type: 'article',
      description:  @article.meta_description || ActionView::Base.full_sanitizer.sanitize(@article.content).truncate(250)
      })
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :category_id, :writer_id, :slug, :image, :meta_description)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

<% if @article.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :title, :class => 'control-label' %>
          <%= f.text_field :title, :class => 'form-control' %>
          <%=f.error_span(:title) %>
        </div>
        <div class="form-group">
          <%= f.label :meta_description, :class => 'control-label' %>
          <%= f.text_area :meta_description, :class => 'form-control', rows: 5,maxlength:"230" %>
          <%=f.error_span(:meta_description) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <div class="form-group">
          <%= f.label :image,"Slider Image", :class => 'control-label' %>
          <% if  @article.image.nil? or @article.image.blank? %>
          <%= f.file_field :image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K'  %>
          <% else %>
          <%= f.file_field :image, :class => 'dropify','data-height'=>"250",'data-max-file-size'=>'500K' , 'data-default-file' => @article.image.url %>
          <% end %>
          <%=f.error_span(:image) %>
    </div>
      </div>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :category_id, :class => 'control-label' %>
          <%= f.select :category_id, Category.all.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2"%>
          <%=f.error_span(:category_id) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :writer_id, :class => 'control-label' %>
          <%= f.select :writer_id, Writer.all.map {|s| [s.title, s.id ]},{:include_blank => '-Choose-'}, :class=>"form-control w-100 select2"%>
          <%=f.error_span(:writer_id) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <%= f.label :content, :class => 'control-label' %>
        <%= f.cktext_area :content, :class => 'form-control',:ckeditor => {toolbar: 'mini'} %>
      <%=f.error_span(:content) %>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        articles_path, :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="card">
    <div class="card-body">
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:title) %></th>
                <th><%= model_class.human_attribute_name(:category_id) %></th>
                <th><%= model_class.human_attribute_name(:writer_id) %></th>
                <th><%= model_class.human_attribute_name(:slug) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @articles.each do |article| %>
              <tr>
                <td><%= link_to article.id, article_path(article) %></td>
                <td><%= article.title %></td>
                <td><%= article.category.title %></td>
                <td><%= article.writer.title %></td>
                <td><%= article.slug %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  article_path(article), :class => 'btn btn-default btn-xs m-1' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_article_path(article), :class => 'btn btn-warning btn-xs m-1' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  article_path(article),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs m-1 btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $(".table").dataTable();
});
</script>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= articles_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
    <%= render :partial => 'form' %>
</div>

app/views/articles/show.html.erb
<section class="article" style="margin-top:10vh;">
  <div class="container">
    <div class="d-block">
      <h1><%= @article.title %></h1>
      <span>Written by <strong> <a href="/writers/<%= @article.writer.slug %>"><%= @article.writer.title %></a></strong> <% if @article.id == 6 %> and Dr. Dewi Agung Tirtaningsih<%end%></span>
    </div>

      <div class="row justify-content-between">
        <div class="pl-3 mb-0">
          <div class="sticky-top mt-4 text-right" style="top:150px;">
            <ul class="list-unstyled text-left d-md-block d-none">
              <li class="social-facebook mb-2">
                <a href="#"  class="fb-share" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=www.behave.rehab/blog/<%= @article.slug %>','facebook-share-dialog','width=626,height=436');return false;">
                  <img src="https://img.icons8.com/material-sharp/32/000000/facebook.png">
                </a>
              </li>
              <li class="social-twitter mb-2">
                <a target="_blank" href="https://twitter.com/intent/tweet?text=<%= @article.title %> , read more at: http://www.behave.rehab/blog/<%= @article.slug %>">
                  <img src="https://img.icons8.com/ios-glyphs/32/000000/twitter.png">
                </a>
              </li>
              <li class="social-wa mb-2">
                <a target="_blank" href="https://wa.me/?text=<%= u "#{@article.title} - http://behave.rehab/#{@article.slug}" %>">
                  <img src="https://img.icons8.com/material/32/000000/whatsapp.png">
                </a>
              </li>
            </ul>
          </div>
          <div class="d-md-none d-sm-block text-center">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#"  class="fb-share" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=www.behave.rehab/blog/<%= @article.slug %>','facebook-share-dialog','width=626,height=436');return false;">
                  <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a target="_blank" href="https://twitter.com/home?status=<%= @article.title %> , read more at: http://www.behave.rehab/blog/<%= @article.slug %>">
                  <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a target="_blank" href="https://wa.me/?text=<%= u "#{@article.title} - http://behave.rehab/#{@article.slug}" %>">
                  <i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12 col-md-8 mt-md-4 mt-sm-0 col mb-3 mb-md-0">
          <div class="article mt-0">
            <%= @article.content.html_safe %>
          </div>
        </div>
        <div class="col-12 col-md-3 mb-3">
          <div class="mb-3" style="top:150px;">
            <h3>Artikel Terkait</h3>
            <hr>
            <% @related.each_with_index do |x, i|  %>
            <a href="<%= blog_detail_path(x) %>">
              <%= x.title %>
            </a>
            <hr>
            <% end %>
          </div>
          <% unless @last_event.end_date < Date.today %>

          <div class="sticky-top " style="top:150px;">
           <h3>Upcoming Event</h3>
           <a href="<%= event_path(@last_event.slug) %>" class="text-dark">
             <img src="<%= @last_event.image %>" alt="<%= @last_event.title %>" class="w-100 mb-3">
             <p >
               <%= @last_event.meta_description %>
             </p>
           </a>
           <a href="<%= event_path(@last_event.slug) %>" class="btn btn-primary">
             Readmore
           </a>
         </div>
         
       <% end %>



        </div>

      </div>

  </div>
</section>