config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :detail_treatments
  resources :treatments
  resources :sliders
  resources :videos
  resources :events
  mount Ckeditor::Engine => '/ckeditor'
  resources :writers
  resources :articles
  resources :categories
  root 'pages#home'
  resources :appointments
  resources :contacts
  get 'app' => "app#index"
  get 'invoice' => "app#invoice"
  get 'pemeriksaan' => "app#pemeriksaan"
  get 'report' => "app#report"
  get 'app-dokter' => "app#app_dokter"
  get 'contact-us', to: 'pages#contact', as: :contact_us
  get 'create-appointment', to: 'pages#create_appointment', as: :create_appointment
  get 'blog', to: 'pages#blog', as: :list_blog
  resources :users
  resources :setups
  devise_for :users,
  path:'user',
  path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  get 'list-page', to: 'pages#index', as: :list_pages
  resources :pages, path: ''
  get '/blog/:id', to: 'articles#show', as: :blog_detail
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :writer
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  
  has_many :articles
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  extend FriendlyId
  friendly_id :title
  mount_uploader :image, ImageUploader

end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  validates :title, presence: true

  mount_uploader :cover_image, ImageUploader

  has_many :sliders, inverse_of: :page
  accepts_nested_attributes_for :sliders, reject_if: :all_blank, allow_destroy: true

end

app/models/setup.rb
class Setup < ApplicationRecord
  mount_uploader :site_image, LogoUploader
  mount_uploader :site_favicon, IconUploader
  validates :site_name, presence: true
  validates :site_title, presence: true
  validates :site_url, presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :page, optional:true
  belongs_to :treatment, optional:true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
    extend FriendlyId
    friendly_id :title

    mount_uploader :image, ImageUploader
    mount_uploader :cover_image, ImageUploader

    has_many :sliders, inverse_of: :treatment
    accepts_nested_attributes_for :sliders, reject_if: :all_blank, allow_destroy: true
    has_many :detail_treatments, inverse_of: :treatment
    accepts_nested_attributes_for :detail_treatments, reject_if: :all_blank, allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true
  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader

  ROLES = {root:'root',administrator:'administrator',doctor:'doctor', editor:'editor'}
  scope :root, -> {where(role: ROLES[:root])}
  scope :administrator, -> {where(role: ROLES[:administrator])}
  scope :doctor, -> {where(role: ROLES[:doctor])}
  scope :editor, -> {where(role: ROLES[:editor])}
  def is_root?
    self.role == ROLES[:root]
  end
  def is_administrator?
    self.role == ROLES[:administrator]
  end
  def is_doctor?
    self.role == ROLES[:doctor]
  end
  def is_editor?
    self.role == ROLES[:editor]
  end
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/writer.rb
class Writer < ApplicationRecord
  extend FriendlyId
  friendly_id :title
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  layout 'admin'
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:youtube_url, :title, :image)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/videos/_form.html.erb
<%= form_for @video, :html => { :class => "form-horizontal video" } do |f| %>

  <% if @video.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :youtube_url,"Url video Youtube", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.url_field :youtube_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:youtube_url) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                videos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/videos/edit.html.erb
<%- model_class = Video -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= categories_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="card">
    <div class="card-body">
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<%- model_class = Video -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= link_to t('.new', :default => t("helpers.links.new")), new_video_path, :class => 'btn btn-success mb-2' %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:id) %></th>
                <th><%= model_class.human_attribute_name(:youtube_url) %></th>
                <th><%= model_class.human_attribute_name(:created_at) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% @videos.each do |video| %>
              <tr>
                <td><%= link_to video.id, video_path(video) %></td>
                <td><%= video.youtube_url %></td>
                <td><%=l video.created_at %></td>
                <td>
                  <%= link_to t('.show', :default => t("helpers.links.show")),
                  video_path(video), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_video_path(video), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  video_path(video),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".table").dataTable();
  });
</script>

app/views/videos/new.html.erb
<%- model_class = Video -%>
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
    </div>
    <div class="col-7 align-self-center">
      <div class="d-flex align-items-center justify-content-end">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= app_path %>">Home</a>
            </li>
            <li class="breadcrumb-item"><a href="<%= articles_path %>"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></a></li>
            <li class="breadcrumb-item">
              <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="card">
    <div class="card-body">
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:youtube_url) %>:</strong></dt>
  <dd><%= @video.youtube_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @video.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @video.image %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              videos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_video_path(@video), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              video_path(@video),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>